Repository CS2113-AY1819S1-T16-3/main, pull requests merged in 2018-10, with the labels that each got.

#18 Schedule & Set Schedule Command
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/commands/SetScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SetScheduleCommandParser.java
Labels: priority.high, type.enhancement, v1.1

#17 CheckCommand added [v1.1]
  src/main/java/seedu/address/logic/commands/CheckCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/logic/commands/CheckCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.high, type.enhancement, v1.1

#21 Update of Developer Guide
  docs/DeveloperGuide.adoc
Labels: update.documentation, v1.1

#22 update README
  README.adoc
Labels: update.documentation, v1.1

#23 Update on Travis-CI, AppVeyor, Coveralls and Codacy badge to link our repo
  README.adoc
Labels: update.documentation, v1.1

#26 v1.2. Implement FilterDepartmentCommand and SortCommand
  src/main/java/seedu/address/logic/commands/FilterDepartmentCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterDepartmentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Department.java
  src/main/java/seedu/address/model/person/DepartmentContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/exceptions/NoEmployeeException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddLeaveCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FilterDepartmentCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterDepartmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/person/DepartmentTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
Labels: priority.high, type.enhancement, v1.2

#60 Update UserGuide.adoc in line with v1.2 deliverables.
  docs/UserGuide.adoc
Labels: update.documentation, v1.2

#62 Update of UserGuide.adoc for v1.2 documentation
  docs/ContactUs.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
Labels: update.documentation, v1.2

#65 V1.2: Schedule & Set Schedule Command
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Version.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/commands/SetPriorityLevelCommand.java
  src/main/java/seedu/address/logic/commands/SetScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/SetScheduleCommandParser.java
  src/main/java/seedu/address/model/SessionManager.java
  src/main/java/seedu/address/model/leave/Date.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/main/java/seedu/address/model/schedule/TimeEnd.java
  src/main/java/seedu/address/model/schedule/TimeStart.java
  src/main/java/seedu/address/model/schedule/Venue.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/storage/XmlAdaptedSchedule.java
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/SetScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/ScheduleCommandParserTest.java
  src/test/java/seedu/address/model/schedule/ScheduleTest.java
  src/test/java/seedu/address/model/schedule/TimeEndTest.java
  src/test/java/seedu/address/model/schedule/TimeStartTest.java
  src/test/java/seedu/address/model/schedule/VenueTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/ScheduleBuilder.java
  src/test/java/seedu/address/testutil/TypicalSchedules.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/seedu/address/ui/HelpWindowTest.java
  src/test/java/seedu/address/ui/PersonCardTest.java
Labels: priority.high, status.ongoing, type.enhancement, v1.2

#25 V1.2: List/ Delete/ Filter Leave Command
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/events/ui/LeavePanelSelectionChangedEvent.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddLeaveCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteLeaveCommand.java
  src/main/java/seedu/address/logic/commands/FilterLeaveCommand.java
  src/main/java/seedu/address/logic/commands/ListLeaveCommand.java
  src/main/java/seedu/address/logic/parser/AddLeaveParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteLeaveCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterLeaveCommandParser.java
  src/main/java/seedu/address/model/LeaveList.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/SessionManager.java
  src/main/java/seedu/address/model/leave/Approval.java
  src/main/java/seedu/address/model/leave/Date.java
  src/main/java/seedu/address/model/leave/Leave.java
  src/main/java/seedu/address/model/leave/NricContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/leave/UniqueLeaveList.java
  src/main/java/seedu/address/storage/XmlAdaptedLeave.java
  src/main/java/seedu/address/ui/LeaveCard.java
  src/main/java/seedu/address/ui/LeaveListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/LeaveListCard.fxml
  src/main/resources/view/LeaveListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddLeaveCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteLeaveCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterLeaveCommandTest.java
  src/test/java/seedu/address/logic/commands/ListLeaveCommandTest.java
  src/test/java/seedu/address/logic/parser/AddLeaveParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteLeaveCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterLeaveCommandParserTest.java
  src/test/java/seedu/address/model/LeaveListTest.java
  src/test/java/seedu/address/model/leave/UniqueLeaveListTest.java
  src/test/java/seedu/address/storage/XmlAdapatedLeaveTest.java
  src/test/java/seedu/address/testutil/LeaveBuilder.java
  src/test/java/seedu/address/testutil/LeaveUtil.java
  src/test/java/seedu/address/testutil/TypicalLeave.java
Labels: priority.high, type.enhancement, v1.2

#66 v1.2. Update of DeveloperGuide.adoc for FilterDepartmentCommand
  docs/DeveloperGuide.adoc
  docs/images/FilterDepartmentCommandSequenceDiagram.png
Labels: update.documentation, v1.2

#67 Updated Dev guide and User guide for Leave related commands
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AddLeaveCommandSequenceDiagram.png
  docs/images/Ui.png
  src/main/resources/images/address_book_32.png
Labels: update.documentation, v1.2

#59 V1.2: CheckCommand Full Implementation (not complete)
  src/main/java/seedu/address/logic/commands/CheckCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/SetPriorityLevelCommand.java
  src/main/java/seedu/address/logic/commands/SetScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CheckCommandParser.java
  src/main/java/seedu/address/model/person/Mode.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/logic/commands/CheckCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CheckCommandParserTest.java
  src/test/java/seedu/address/model/person/ModeTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: priority.high, status.ongoing, type.enhancement, v1.2

#68 V1.2 update developer guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ArchitectureDiagram.pptx
  docs/diagrams/ImplementPlvlRestrictionDiagram.xml
  docs/diagrams/LogicComponentSequenceDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/images/Architecture.png
  docs/images/DeletePersonSdForLogic.png
  docs/images/ImplementPlvlRestrictionSequenceDiagram.png
  docs/images/ModelClassDiagram.png
Labels: update.documentation

#73 Minor Optimization Fix
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/SetScheduleCommandParserSequenceDiagram.png
  docs/images/SetScheduleCommandSequenceDiagram.png
  docs/team/chongyu.adoc
  docs/team/hafizuddin.adoc
  docs/team/jinyao.adoc
  docs/team/pinjuen.adoc
  docs/team/woonhian.adoc
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/commands/SetScheduleCommand.java
  src/main/java/seedu/address/logic/parser/SetScheduleCommandParser.java
  src/main/java/seedu/address/model/SessionManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedSchedule.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/SetScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/ScheduleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SetScheduleCommandParserTest.java
  src/test/java/seedu/address/model/schedule/VenueTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/storage/XmlAdaptedScheduleTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalSchedules.java
Labels: status.ongoing, update.testcases

#71 V1.2 - User/Developer Guide update
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/CheckCommandSequenceDiagram.png
Labels: update.documentation

#76 RepoSense Config
  .gitignore
  _reposense/config.json
  src/main/java/seedu/address/logic/commands/SetScheduleCommand.java
  src/test/java/seedu/address/model/schedule/VenueTest.java
Labels: bug

#77 Update RepoSense
  _reposense/config.json
  docs/DeveloperGuide.adoc
Labels: update.documentation

#78 Update of DeveloperGuide
  docs/DeveloperGuide.adoc
Labels: update.documentation

#79 Restructured SessionManager to be non-static and singleton class
  src/main/java/seedu/address/commons/events/model/SessionChangedEvent.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddLeaveCommand.java
  src/main/java/seedu/address/logic/commands/CheckLoginStatusCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteLeaveCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/LogoutCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/commands/SetPriorityLevelCommand.java
  src/main/java/seedu/address/logic/commands/SetScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddLeaveParser.java
  src/main/java/seedu/address/logic/parser/SetPriorityLevelCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/SessionManager.java
  src/main/java/seedu/address/model/leave/Leave.java
  src/main/java/seedu/address/session/Session.java
  src/main/java/seedu/address/session/SessionManager.java
  src/main/java/seedu/address/storage/XmlAdaptedLeave.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/address/logic/commands/AddLeaveCommandTest.java
  src/test/java/seedu/address/logic/commands/CheckLoginStatusTest.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/SetPriorityLevelCommandTest.java
  src/test/java/seedu/address/logic/parser/SetPriorityLevelCommandParserTest.java
  src/test/java/seedu/address/testutil/LeaveBuilder.java
  src/test/java/systemtests/SessionHelper.java
Labels: update.code, update.testcases, v1.3

#81 V1.3: Edit leave application for approval
  src/main/java/seedu/address/commons/events/model/LeaveListChangedEvent.java
  src/main/java/seedu/address/logic/commands/AddLeaveCommand.java
  src/main/java/seedu/address/logic/commands/DeleteLeaveCommand.java
  src/main/java/seedu/address/logic/commands/EditLeaveCommand.java
  src/main/java/seedu/address/logic/commands/FilterLeaveCommand.java
  src/main/java/seedu/address/logic/commands/ListLeaveCommand.java
  src/main/java/seedu/address/logic/parser/AddLeaveParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ApproveLeaveCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteLeaveCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterLeaveCommandParser.java
  src/main/java/seedu/address/logic/parser/RejectLeaveCommandParser.java
  src/main/java/seedu/address/model/LeaveList.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyLeaveList.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/VersionedLeaveList.java
  src/main/java/seedu/address/model/leave/Approval.java
  src/main/java/seedu/address/model/leave/Date.java
  src/main/java/seedu/address/model/leave/EmployeeId.java
  src/main/java/seedu/address/model/leave/Leave.java
  src/main/java/seedu/address/model/leave/NricContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/leave/UniqueLeaveList.java
  src/main/java/seedu/address/session/Session.java
  src/main/java/seedu/address/session/SessionManager.java
  src/main/java/seedu/address/storage/LeaveListStorage.java
  src/main/java/seedu/address/storage/XmlAdaptedLeave.java
  src/main/java/seedu/address/storage/XmlLeaveListStorage.java
  src/main/java/seedu/address/storage/XmlSerializableLeaveList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddLeaveCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteLeaveCommandTest.java
  src/test/java/seedu/address/logic/commands/EditLeaveCommandTest.java
  src/test/java/seedu/address/logic/commands/EditLeaveDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FilterLeaveCommandTest.java
  src/test/java/seedu/address/logic/commands/ListLeaveCommandTest.java
  src/test/java/seedu/address/logic/parser/AddLeaveParserTest.java
  src/test/java/seedu/address/logic/parser/ApproveLeaveCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteLeaveCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterLeaveCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RejectLeaveCommandParserTest.java
  src/test/java/seedu/address/model/LeaveListTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/XmlAdapatedLeaveTest.java
  src/test/java/seedu/address/testutil/EditLeaveDescriptorBuilder.java
  src/test/java/seedu/address/testutil/LeaveBuilder.java
  src/test/java/seedu/address/testutil/LeaveListBuilder.java
  src/test/java/seedu/address/testutil/LeaveUtil.java
  src/test/java/seedu/address/testutil/TypicalLeave.java
Labels: priority.high, update.code, update.testcases, v1.3

#84 Modified editCommand to only edit your own particulars, and not others
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ImplementPlvlRestrictionDiagram.xml
  docs/diagrams/ImplementPlvlRestrictionSequenceDiagram.xml
  docs/images/ImplementPlvlRestrictionSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ResetCommand.java
  src/main/java/seedu/address/logic/commands/SetDepartmentCommand.java
  src/main/java/seedu/address/logic/commands/SetPriorityLevelCommand.java
  src/main/java/seedu/address/logic/commands/SetScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/prioritylevel/PriorityLevel.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ResetCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: type.enhancement, update.code, update.testcases, v1.3

#90 V1.3: Updated User Guide
  docs/UserGuide.adoc
  src/test/java/seedu/address/logic/commands/EditLeaveCommandTest.java
  src/test/java/seedu/address/logic/parser/ApproveLeaveCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RejectLeaveCommandParserTest.java
Labels: update.documentation, update.testcases, v1.3

#92 V1.3 - checkCommand Full Implementation
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CheckCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/SetDepartmentCommand.java
  src/main/java/seedu/address/logic/commands/SetPriorityLevelCommand.java
  src/main/java/seedu/address/logic/commands/SetScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CheckCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/CheckedInTime.java
  src/main/java/seedu/address/model/person/Mode.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/WorkingRate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/logic/commands/CheckCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CheckCommandParserTest.java
  src/test/java/seedu/address/model/person/CheckedInTimeTest.java
  src/test/java/seedu/address/model/person/WorkingRateTest.java
  src/test/java/seedu/address/storage/XmlSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
Labels: type.enhancement, update.code, v1.3

#89 Update docs/UserGuide.adoc
  docs/UserGuide.adoc
  docs/team/hafizuddin.adoc
  docs/team/jinyao.adoc
  docs/team/pinjuen.adoc
  docs/team/woonhian.adoc
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddLeaveCommandTest.java
  src/test/java/seedu/address/logic/commands/CheckCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditLeaveCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/SetScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/VersionedAddressBookTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: update.code, update.documentation

#95 v1.3. Updated UserGuide with screenshots
  docs/UserGuide.adoc
  docs/images/FilterDepartmentAfter1.png
  docs/images/FilterDepartmentAfter2.png
  docs/images/FilterDepartmentBefore1.png
  docs/images/FilterDepartmentBefore2.png
  docs/images/ListDepartmentAfter.png
  docs/images/ListDepartmentBefore.png
  docs/images/SetDepartmentAfter.png
  docs/images/SetDepartmentBefore.png
  docs/images/SortAfter1.png
  docs/images/SortAfter2.png
  docs/images/SortBefore1.png
  docs/images/SortBefore2.png
Labels: update.documentation, v1.3

#97 Minor updates
  src/main/java/seedu/address/model/person/Person.java
Labels: update.code

#93 Updated Readme and User Guide
  README.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/images/acceptedleave.png
  docs/images/approvecmd.png
  docs/images/approved.png
  docs/images/deletedleave.png
  docs/images/deleteleavecmd.png
  docs/images/deletingleave.png
  docs/images/filterleave.png
  docs/images/filterleavecmd.png
  docs/images/leave.png
  docs/images/listedleave.png
  docs/images/listleave.png
  docs/images/rejectcmd.png
  docs/images/rejected.png
Labels: update.documentation, v1.3

#94 User Guide Update
  docs/UserGuide.adoc
  docs/images/checkedIn.PNG
  docs/images/checkedOut.PNG
  docs/images/inStatus.PNG
  docs/images/outStatus.PNG
Labels: update.documentation, v1.3

#98 v1.3 QoL Changes
  docs/UserGuide.adoc
  docs/images/UserGuide.png
  docs/images/schedule_cmd.png
  src/main/java/seedu/address/commons/events/model/SessionChangedEvent.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddLeaveCommand.java
  src/main/java/seedu/address/logic/commands/CheckCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditLeaveCommand.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/commands/SetScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/SetScheduleCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/main/java/seedu/address/model/schedule/TimeEnd.java
  src/main/java/seedu/address/model/schedule/TimeStart.java
  src/main/java/seedu/address/model/schedule/Venue.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/storage/XmlAdaptedSchedule.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/SetScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SetScheduleCommandParserTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/storage/XmlAdaptedScheduleTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
Labels: type.enhancement, update.code, update.documentation, v1.3

#96 v1.3: Further updates to UserGuide.adoc
  docs/UserGuide.adoc
  docs/images/loginTextBox.png
  docs/images/login_success_screenShot.png
  docs/images/setOwnPlvl_failed_screenShot.png
  docs/images/setPlvl_failed_screenShot.png
  docs/images/setPlvl_success_screenShot.png
Labels: update.documentation, v1.3

#101 Removed incorrect Note W.R.T. Priority Level requirements
  docs/UserGuide.adoc
Labels: update.documentation, v1.3
