Repository CS2113-AY1819S1-T16-3/main, pull requests merged in 2018-11, with the labels that each got.

#105 V1.3: bug fixes
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/commands/SetScheduleCommand.java
  src/main/java/seedu/address/session/SessionManager.java
Labels: bug, v1.3

#104 v1.3.1 UserGuide update
  docs/UserGuide.adoc
  docs/images/FilterDepartmentAfter1.png
  docs/images/FilterDepartmentAfter2.png
  docs/images/FilterDepartmentBefore1.png
  docs/images/FilterDepartmentBefore2.png
  docs/images/ListDepartmentAfter.png
  docs/images/ListDepartmentBefore.png
  docs/images/SetDepartmentBefore.png
  docs/images/SortAfter1.png
  docs/images/SortAfter2.png
  docs/images/SortBefore1.png
  docs/images/SortBefore2.png
  docs/images/acceptedleave.png
  docs/images/approvecmd.png
  docs/images/deletedleave.png
  docs/images/deleteleavecmd.png
  docs/images/deletingleave.png
  docs/images/filterleavecmd.png
  docs/images/leave.png
  docs/images/listleave.png
  docs/images/rejectcmd.png
Labels: update.documentation, v1.3

#107 Added invalid calendar date check
  src/main/java/seedu/address/model/VersionedLeaveList.java
  src/main/java/seedu/address/model/leave/Date.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: update.code, update.testcases

#108 Browser removed (Done)
  docs/images/Ui.png
  docs/images/bankAB.png
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: update.code

#109 Updated userguide
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/images/approved.png
  docs/images/deleteresult.png
  docs/images/deletingleave.png
  docs/images/filteredleave.png
  docs/images/filterleave.png
  docs/images/listedleave.png
  docs/images/reject.png
  docs/images/rejected.png
Labels: update.documentation

#110 Updated screenshots for UserGuide
  docs/UserGuide.adoc
  docs/images/SetDepartmentAfter.png
  docs/images/SetDepartmentBefore.png
  docs/images/login_success_screenShot.png
  docs/images/setPlvl_success_screenShot.png
Labels: update.documentation

#129 Updated codes related to PE1 issue reports
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/parser/SetDepartmentCommandParser.java
  src/main/java/seedu/address/model/person/Department.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/parser/SetDepartmentCommandParserTest.java
Labels: update.code

#133 Update code
  src/main/java/seedu/address/logic/parser/SetDepartmentCommandParser.java
Labels: update.code

#132 V1.4: Fix bugs found in PE1
  src/main/java/seedu/address/logic/parser/AddLeaveParser.java
  src/main/java/seedu/address/model/leave/Date.java
  src/test/java/seedu/address/logic/parser/AddLeaveParserTest.java
Labels: update.code, update.testcases, v1.4

#131 V1.4 Changes Inspired by PE
  docs/UserGuide.adoc
  leavelist.xml
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/parser/SetScheduleCommandParserTest.java
  src/test/java/seedu/address/model/schedule/ScheduleTest.java
Labels: update.code, update.documentation, v1.4

#134 Modified PriorityLevelEnum such that Administrator is now of a higher Priority Level than I.T. Unit.
  docs/AboutUs.adoc
  docs/team/hafizuddin-nus.adoc
  docs/team/jylee-git.adoc
  docs/team/speezy37.adoc
  src/main/java/seedu/address/logic/commands/ResetCommand.java
  src/main/java/seedu/address/model/prioritylevel/PriorityLevel.java
  src/main/java/seedu/address/model/prioritylevel/PriorityLevelEnum.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/session/Session.java
  src/main/java/seedu/address/session/SessionManager.java
  src/test/java/seedu/address/logic/commands/EditLeaveCommandTest.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/ResetCommandTest.java
  src/test/java/seedu/address/logic/commands/SetPriorityLevelCommandTest.java
  src/test/java/seedu/address/model/person/NricTest.java
  src/test/java/seedu/address/model/person/PrioritylevelTest.java
Labels: enhancement, update.code, v1.4

#137 v1.4 Update documentation
  docs/UserGuide.adoc
  docs/team/woonhian.adoc
  src/main/java/seedu/address/logic/commands/FilterDepartmentCommand.java
  src/main/java/seedu/address/logic/commands/ListDepartmentCommand.java
  src/main/java/seedu/address/logic/commands/SetDepartmentCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/FilterDepartmentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetDepartmentCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/person/Department.java
  src/main/java/seedu/address/model/person/DepartmentContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/FilterDepartmentCommandTest.java
  src/test/java/seedu/address/logic/commands/ListDepartmentCommandTest.java
  src/test/java/seedu/address/logic/commands/SetDepartmentCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterDepartmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SetDepartmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/person/DepartmentTest.java
Labels: update.documentation, v1.4

#136 v1.4: Update documentation
  build.gradle
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/jylee-git.adoc
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/session/SessionManager.java
Labels: update.documentation, v1.4

#140 My adoc update
  docs/team/speezy37.adoc
Labels: update.documentation, v1.4

#102 V1.4 Check Command Update
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/CheckCommandSequenceDiagram.png
  docs/images/checkedIn.PNG
  docs/images/checkedInStatus.png
  docs/images/checkedOut.PNG
  docs/images/checkedOutStatus.png
  docs/images/inStatus.PNG
  docs/images/outStatus.PNG
  src/main/java/seedu/address/logic/commands/CheckCommand.java
  src/main/java/seedu/address/logic/parser/CheckCommandParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/logic/commands/CheckCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CheckCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: enhancement, update.documentation, v1.4

#138 V1.4: Update portfolio
  docs/team/jylee-git.adoc
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetPriorityLevelCommandParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: update.documentation, v1.4

#146 v1.4 Developer Guide updates
  docs/DeveloperGuide.adoc
Labels: update.documentation, v1.4

#139 v1.4.1 Update documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/FilterDepartmentAfter1.png
  docs/images/FilterDepartmentAfter2.png
  docs/images/FilterDepartmentBefore1.png
  docs/images/FilterDepartmentBefore2.png
  docs/images/ListDepartmentBefore.png
  docs/images/SetDepartmentAfter.png
  docs/images/SetDepartmentBefore.png
  docs/images/SortAfter1.png
  docs/images/SortAfter2.png
  docs/images/SortBefore1.png
  docs/images/SortBefore2.png
  docs/team/woonhian.adoc
Labels: update.documentation, v1.4

#147 Updated check command + documentation
  docs/DeveloperGuide.adoc
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/address/logic/commands/CheckCommand.java
Labels: enhancement, update.documentation, v1.4

#149 v1.4 Updates on DeveloperGuide
  docs/DeveloperGuide.adoc
Labels: update.documentation, v1.4

#148 V1.4: Dev Guide Documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ModelComponentClassBetterOopDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/ModelClassBetterOopDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/Ui.png
  docs/images/UiClassDiagram.png
  docs/images/approved.png
  docs/images/deletedleave.png
  docs/images/deleteresult.png
  docs/images/deletingleave.png
  docs/images/filteredleave.png
  docs/images/filterleavecmd.png
  docs/images/listedleave.png
  docs/images/reject.png
  docs/team/hafizuddin-nus.adoc
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlFileStorage.java
Labels: update.code, update.documentation, v1.4

#150 Update UG / DG
  docs/DeveloperGuide.adoc
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/images/StorageClassDiagram.png
  docs/team/speezy37.adoc
Labels: update.documentation, v1.4

#144 V1.4 update documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/SessionComponentClassDiagram.xml
  docs/images/SessionComponentClassDiagram.png
  docs/images/login_success_screenShot.png
  docs/images/setPlvl_success_screenShot.png
  docs/team/jylee-git.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/session/Session.java
  src/main/java/seedu/address/session/SessionManager.java
Labels: update.documentation, v1.4

#152 Minor update on developer guide
  docs/DeveloperGuide.adoc
Labels: update.documentation, v1.4

#151 v1.4. Minor changes to Developer Guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/UserGuide.png
Labels: update.documentation, v1.4

#155 Changes to user guide, dev guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: update.documentation, v1.4

#159 v1.4 Fix issues related bugs
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: update.documentation, v1.4

#161 V1.4 Interval Review Changes
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/schedule_cmd.png
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
Labels: update.documentation, v1.4

#163 V1.4: Fixed discrepancies in DeveloperGuide and UserGuide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
Labels: update.documentation, v1.4

#160 Fixed issues raised.
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/commons/events/ui/LeavePanelSelectionChangedEvent.java
  src/main/java/seedu/address/logic/commands/EditLeaveCommand.java
  src/main/java/seedu/address/ui/LeaveListPanel.java
Labels: update.documentation, v1.4

#164 Adoc overview update
  docs/team/speezy37.adoc
Labels: update.documentation, v1.4
